### ISSUE TITLE
Application Does Not Start (The system cannot find the file specified)

### ISSUE THREAD

**Issue by cometbeetle** [micahmo/WgServerforWindows#102]
I've been running WgServerforWindows on Windows Server 2019 for some time now without problems. But, for some reason, it stopped working yesterday and started throwing the error "The system cannot find the file specified" upon launching the app. 

The detailed error log it gives is as follows:

System.ComponentModel.Win32Exception (2): **The system cannot find the file specified.**
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at WgAPI.WireGuardExe.ExecuteCommand(WireGuardCommand command, Int32& exitCode) in D:\a\WgServerforWindows\WgServerforWindows\WgAPI\WireGuardExe.cs:line 94
   at WgServerforWindows.Models.NewNetNatPrerequisite.get_IsSupported() in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Models\NewNetNatPrerequisite.cs:line 209
   at WgServerforWindows.MainWindow..ctor() in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\MainWindow.xaml.cs:line 91
   at WgServerforWindows.Controls.SplashScreen.<>c.<Window_Loaded>b__1_0() in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Controls\SplashScreen.xaml.cs:line 25
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

I've tried several troubleshooting steps, but I'm not exactly sure of what the problem is. Any help would be greatly appreciated. 

Thanks!

**Comment by micahmo** [comment]
Hi @cometbeetle, I'm sorry about this! I believe the application is failing at its very first attempt to use PowerShell during startup. This could be because your PATH environment variable is corrupted.

Maybe you can try a few things to see if other applications can find PowerShell. For example, can you open the Run box from the Start menu and try to execute `powershell.exe` from there?

![image](https://user-images.githubusercontent.com/7417301/224688037-ee093ebb-02ef-4390-a7e7-43be59f137ea.png)

Or open PowerShell from the Start menu and then try to create a new shell instance within it.

Let me know!

---

https://github.com/micahmo/WgServerforWindows/blob/7375aeda0e2fd3e8f40b2da2fd33b245931973da/WgServerforWindows/Models/NewNetNatPrerequisite.cs#L204-L207

**Comment by cometbeetle** [comment]
Wow! That turned out to be exactly the problem. 

I just re-added PowerShell to PATH (it had been removed for some reason), and now everything works just as before. 

Thanks so much for your help!

**Comment by micahmo** [comment]
Happy to help!

**Comment by demartis** [comment]
Hello, same here! Powershell is on PATH.

System.ComponentModel.Win32Exception (2): **The system cannot find the file specified**.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at WgAPI.WireGuardExe.ExecuteCommand(WireGuardCommand command, Int32& exitCode) in D:\a\WgServerforWindows\WgServerforWindows\WgAPI\WireGuardExe.cs:line 94
   at WgServerforWindows.Models.NewNetNatPrerequisite.get_IsSupported() in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Models\NewNetNatPrerequisite.cs:line 226
   at WgServerforWindows.MainWindow..ctor() in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\MainWindow.xaml.cs:line 92
   at WgServerforWindows.Controls.SplashScreen.<>c.<Window_Loaded>b__1_0() in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Controls\SplashScreen.xaml.cs:line 25
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
