### ISSUE TITLE
Error  The application has encountered an unexpected error.

### ISSUE THREAD

**Issue by sgx12321** [micahmo/WgServerforWindows#119]
Copy Details
System.ComponentModel.Win32Exception (2): 系统找不到指定的文件。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at WgAPI.WireGuardExe.ExecuteCommand(WireGuardCommand command, Int32& exitCode) in D:\a\WgServerforWindows\WgServerforWindows\WgAPI\WireGuardExe.cs:line 94
   at WgServerforWindows.Models.NewNetNatPrerequisite.get_IsSupported() in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Models\NewNetNatPrerequisite.cs:line 226
   at WgServerforWindows.MainWindow..ctor() in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\MainWindow.xaml.cs:line 92
   at WgServerforWindows.Controls.SplashScreen.<>c.<Window_Loaded>b__1_0() in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Controls\SplashScreen.xaml.cs:line 25
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

![1](https://github.com/micahmo/WgServerforWindows/assets/65528798/bb926b6f-2dfd-4bf1-8e4c-cb9614db2050)

**Comment by micahmo** [comment]
Hi @sgx12321, it looks like you closed this issue. Are you all set?
