### ISSUE TITLE
Cannot enable NAT anymore after some tries.

### ISSUE THREAD

**Issue by Lalarian** [micahmo/WgServerforWindows#124]
Hello!

I just installed it freshly and experimented a bit.
After some tries thre was an error when enabling NAT.
Since it appeared the first time I could not get rid of it anymore, so it's not possible to enabel NAT through the GUI anymore.
I deleted the whole configuratin diretory, uninstalled the tunnel and uninstalled the WG serves, but this did not help.

Here's the error:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: New-NetIPAddress : Fehlendes Argument fr den Parameter "IPAddress". Geben Sie einen Parameter vom Typ "System.String" 
an, und versuchen Sie es erneut.
In Zeile:1 Zeichen:18
+ New-NetIPAddress -IPAddress -PrefixLength 32 -InterfaceIndex 16
+                  ~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-NetIPAddress], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,New-NetIPAddress
 

   at WgServerforWindows.Models.NewNetNatPrerequisite.Resolve(String serverDataPath) in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Models\NewNetNatPrerequisite.cs:line 103
   at WgServerforWindows.Models.NewNetNatPrerequisite.Resolve() in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Models\NewNetNatPrerequisite.cs:line 73
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at GalaSoft.MvvmLight.Helpers.WeakAction.Execute()
   at GalaSoft.MvvmLight.Command.RelayCommand.Execute(Object parameter)
   at Xceed.Wpf.Toolkit.DropDownButton.RaiseCommand()
   at Xceed.Wpf.Toolkit.DropDownButton.OnClick()
   at Xceed.Wpf.Toolkit.DropDownButton.DropDownButton_Click(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

System.Exception: New-NetIPAddress : Fehlendes Argument fr den Parameter "IPAddress". Geben Sie einen Parameter vom Typ "System.String" 
an, und versuchen Sie es erneut.
In Zeile:1 Zeichen:18
+ New-NetIPAddress -IPAddress -PrefixLength 32 -InterfaceIndex 16
+                  ~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-NetIPAddress], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,New-NetIPAddress
 

   at WgServerforWindows.Models.NewNetNatPrerequisite.Resolve(String serverDataPath) in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Models\NewNetNatPrerequisite.cs:line 103
   at WgServerforWindows.Models.NewNetNatPrerequisite.Resolve() in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Models\NewNetNatPrerequisite.cs:line 73


```

**Comment by Lalarian** [comment]
Well, someho it disappered after somer more triesd ...

**Comment by micahmo** [comment]
Hi @Lalarian, glad to see the issue disappeared! Windows can be finnicky like that!
