### ISSUE TITLE
NAT routing issue

### ISSUE THREAD

**Issue by YoleeR12** [micahmo/WgServerforWindows#168]
So um, basically whenever I press on enable NAT I get greeted with this error

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: New-NetIPAddress : Missing an argument for parameter 'IPAddress'. Specify a parameter of type 'System.String' and try 
again.
At line:1 char:18
+ New-NetIPAddress -IPAddress -PrefixLength 32 -InterfaceIndex 33
+                  ~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-NetIPAddress], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,New-NetIPAddress
 

   at WgServerforWindows.Models.NewNetNatPrerequisite.Resolve(String serverDataPath) in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Models\NewNetNatPrerequisite.cs:line 103
   at WgServerforWindows.Models.NewNetNatPrerequisite.Resolve() in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Models\NewNetNatPrerequisite.cs:line 73
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at GalaSoft.MvvmLight.Helpers.WeakAction.Execute()
   at GalaSoft.MvvmLight.Command.RelayCommand.Execute(Object parameter)
   at Xceed.Wpf.Toolkit.DropDownButton.RaiseCommand()
   at Xceed.Wpf.Toolkit.DropDownButton.OnClick()
   at Xceed.Wpf.Toolkit.DropDownButton.DropDownButton_Click(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

System.Exception: New-NetIPAddress : Missing an argument for parameter 'IPAddress'. Specify a parameter of type 'System.String' and try 
again.
At line:1 char:18
+ New-NetIPAddress -IPAddress -PrefixLength 32 -InterfaceIndex 33
+                  ~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-NetIPAddress], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,New-NetIPAddress
 

   at WgServerforWindows.Models.NewNetNatPrerequisite.Resolve(String serverDataPath) in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Models\NewNetNatPrerequisite.cs:line 103
   at WgServerforWindows.Models.NewNetNatPrerequisite.Resolve() in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Models\NewNetNatPrerequisite.cs:line 73

And Ima be completly real I have no idea what that means, I did read somewhere that I needed windows 11 and and version 23H2 something I do have, and hyper-V enabled?? that I also do have enabled so idk what this is about really 
![Screenshot 2024-06-06 212713](https://github.com/micahmo/WgServerforWindows/assets/171977308/303dca6e-b5fb-47a3-98cf-d85c048d1169)
![Screenshot 2024-06-06 212742](https://github.com/micahmo/WgServerforWindows/assets/171977308/b8eea2d4-2ed9-4950-b6bd-2fbdeb182df2)

if you need anymore info I gotchu I just don't really know what to do now

**Comment by ZiotecH** [comment]
You're missing an IP-address when calling the command.
Have you filled all of the fields in the installer properly?
