### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by demartis** [micahmo/WgServerforWindows#171]
Hello, same issue of https://github.com/micahmo/WgServerforWindows/issues/102 here!
Powershell is in PATH. The program fails at its very first attempt to start 

System.ComponentModel.Win32Exception (2): **The system cannot find the file specified**.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at WgAPI.WireGuardExe.ExecuteCommand(WireGuardCommand command, Int32& exitCode) in D:\a\WgServerforWindows\WgServerforWindows\WgAPI\WireGuardExe.cs:line 94
   at WgServerforWindows.Models.NewNetNatPrerequisite.get_IsSupported() in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Models\NewNetNatPrerequisite.cs:line 226
   at WgServerforWindows.MainWindow..ctor() in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\MainWindow.xaml.cs:line 92
   at WgServerforWindows.Controls.SplashScreen.<>c.<Window_Loaded>b__1_0() in D:\a\WgServerforWindows\WgServerforWindows\WgServerforWindows\Controls\SplashScreen.xaml.cs:line 25
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

_Originally posted by @demartis in https://github.com/micahmo/WgServerforWindows/issues/102#issuecomment-2408607535_

**Comment by micahmo** [comment]
Hi @demartis, thanks for posting the issue. If PowerShell is in the path, then I'm not sure why WS4W can't find it. Can you launch PowerShell from the Run box as suggested in the other issue?

**Comment by hiidemo** [comment]
add "C:\Windows\System32\WindowsPowerShell\v1.0" to PATH environment variable
