### ISSUE TITLE
No internet and with latest update of windows 10, i can't enable internet sharing:

### ISSUE THREAD

**Issue by Owned67** [micahmo/WgServerforWindows#39]
Hello,

i've no internet when my client is enabled...

server status:
`interface: wg_server
  public key: eQqR5N/GnJgu+Yw8mRIDtZpublickey
  private key: (hidden)
  listening port: 51820

peer: v1RLoLK8Lynw9yvf20aHlN57ddApublickey
  preshared key: (hidden)
  endpoint: 192.168.1.254:55022
  allowed ips: 10.253.0.3/32
  latest handshake: 3 hours, 34 minutes ago
  transfer: 18.27 KiB received, 301.00 KiB sent
  persistent keepalive: every 25 seconds`

Im behing a freebox, port 51820 is opened

Firewall is off

for: endpoint: 192.168.1.254:55022

i've tryp iplan, ipwan and same

in client log:
`2022-04-13 20:44:27.801: [TUN] [wg_server] Handshake for peer 1 (no address) did not complete after 5 seconds, retrying (try 12)
2022-04-13 20:44:27.801: [TUN] [wg_server] Sending handshake initiation to peer 1 (no address)
2022-04-13 20:44:28.817: [TUN] [wg_server] Handshake for peer 2 (192.168.1.254:55022) did not complete after 5 seconds, retrying (try 13)
2022-04-13 20:44:28.817: [TUN] [wg_server] Sending handshake initiation to peer 2 (192.168.1.254:55022)
2022-04-13 20:44:32.861: [TUN] [wg_server] Handshake for peer 1 (no address) did not complete after 5 seconds, retrying (try 13)
2022-04-13 20:44:32.861: [TUN] [wg_server] Sending handshake initiation to peer 1 (no address)
2022-04-13 20:44:33.907: [TUN] [wg_server] Handshake for peer 2 (192.168.1.254:55022) did not complete after 5 seconds, retrying (try 14)
2022-04-13 20:44:33.907: [TUN] [wg_server] Sending handshake initiation to peer 2 (192.168.1.254:55022)`

edit: with latest update of windows 10, i can't enable internet sharing:
`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Runtime.InteropServices.COMException (0x80040201): Un événement n’a pu invoquer aucun des abonnés. (0x80040201)
   at NETCONLib.INetSharingConfiguration.EnableSharing(tagSHARINGCONNECTIONTYPE Type)
   at WireGuardServerForWindows.Models.InternetSharingPrerequisite.Resolve(String networkToShare) in C:\Users\micah\source\repos\WireGuardServerForWindows\WireGuardServerForWindows\Models\InternetSharingPrerequisite.cs:line 146
   at WireGuardServerForWindows.Models.InternetSharingPrerequisite.Resolve() in C:\Users\micah\source\repos\WireGuardServerForWindows\WireGuardServerForWindows\Models\InternetSharingPrerequisite.cs:line 52
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at GalaSoft.MvvmLight.Helpers.WeakAction.Execute()
   at GalaSoft.MvvmLight.Command.RelayCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

System.Runtime.InteropServices.COMException (0x80040201): Un événement n’a pu invoquer aucun des abonnés. (0x80040201)
   at NETCONLib.INetSharingConfiguration.EnableSharing(tagSHARINGCONNECTIONTYPE Type)
   at WireGuardServerForWindows.Models.InternetSharingPrerequisite.Resolve(String networkToShare) in C:\Users\micah\source\repos\WireGuardServerForWindows\WireGuardServerForWindows\Models\InternetSharingPrerequisite.cs:line 146
   at WireGuardServerForWindows.Models.InternetSharingPrerequisite.Resolve() in C:\Users\micah\source\repos\WireGuardServerForWindows\WireGuardServerForWindows\Models\InternetSharingPrerequisite.cs:line 52

`

**Comment by JinBeast** [comment]
Have you tried manually enabling it?

**Comment by JinBeast** [comment]
in configuration use network reset

**Comment by Owned67** [comment]
i don't found this option :x

**Comment by xor-128** [comment]
I had the same issue

**Comment by micahmo** [comment]
When Internet Sharing gets stuck, it can be necessary to manually enable it. Check out the workaround described here.

https://github.com/micahmo/WgServerforWindows#inability-to-enable-internet-sharing

**Comment by JP95Git** [comment]
I have to use "Internet Sharing" because NAT requires HyperV. If this is active, my virtual machines in VirtualBox run very slow.

Unfortunately, I regularly encounter the problem, that WG4W can't enable "Internet Sharing" (same error code as Owned67). Each time I have to manually follow the workaround to bring WG4W "back to life". What prevents you from automate this workaround (or find a better solution) in WG4W?

**Comment by micahmo** [comment]
> What prevents you from automate this workaround (or find a better solution) in WG4W?

Unfortunately, we're limited by what the Windows API provides. WS4W is attempting to enable Internet Sharing, but Windows is reporting an error. The workaround is just performing the same action through the Windows system UI, which somehow works better than the API. When this issue first cropped up, I looked into workarounds, but this is "the way" to do it in Windows. Of course, I'd be happy to be wrong about this if someone comes up with something better.

The real "better solution" is NAT routing, but you've explained why that wouldn't work for you. I'm sorry. 😞

**Comment by JP95Git** [comment]
@micahmo 
Thanks, but this does not help.

Haven't developed with the Windows API for 20 years, but I try to fix it. Here is how I can reproducible break WS4W:

Internet sharing works, restart works as expected;
```
C:\Program Files (x86)\WS4W>ws4w restartinternetsharing
Internet sharing is already enabled. Disabling...
Enabling internet sharing with network 'WLAN'.
Command executed successfully.
```

Share with an non existing internet connection, because after each reboot my internet connection is shared with wg_server_\<random number\> instead of wg_server:
```
C:\Program Files (x86)\WS4W>ws4w restartinternetsharing --network random-name
Internet sharing is already enabled. Disabling...
Enabling internet sharing with network 'random-name'.
Command did not complete successfully.
```

Restarting fails, as expected:
```
C:\Program Files (x86)\WS4W>ws4w restartinternetsharing
Cannot restart internet sharing since no network is currently shared. Specify a network to share with --network.
Command did not complete successfully.
```

Provide the previously shared network again, this does not work using ws4w, users currently have to manually do this step using the windows gui:
```
C:\Program Files (x86)\WS4W>ws4w restartinternetsharing --network WLAN
Enabling internet sharing with network 'WLAN'.
Command did not complete successfully.
```

**Comment by micahmo** [comment]
Hey @JP95Git, thank you so much for the detailed repro steps, that is very helpful! And thank you for volunteering to take a look at the code. I use Visual Studio. Any version is fine but the latest (major) release is 2022. I build on Windows (again, pretty much any version, 10 or 11 is fine).

**Comment by micahmo** [comment]
Hey @JP95Git, did you ever get a chance to look into this issue further?

**Comment by JP95Git** [comment]
@micahmo 
I did not look into the issue any further, because it is no longer a problem for me.

I had reinstalled Windows 10 a few months ago to use UEFI. WS4W and the settings were copied. Since then the problem has disappeared.

Since I also maintain other projects (under a different name) my free time is very limited, so I did not look into the problem further.

**Comment by micahmo** [comment]
Hey @JP95Git, thanks so much for jumping back in here to provide an update. I'm glad your issue was resolved after reinstalling Windows. Sometimes it's just quirky like that! No need to explain not looking into the issue further. As long as things are working for you, then I'm happy. I will go ahead and close out this issue. 😊
